// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN-8XIFuncrVKZU9nYSUBBxoQx5YvZYH4',
    appId: '1:544154185532:web:09a1d95b831dc7916bb839',
    messagingSenderId: '544154185532',
    projectId: 'tigris-notes-app',
    authDomain: 'tigris-notes-app.firebaseapp.com',
    storageBucket: 'tigris-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsXY5CivDeDJ5Rz91SIHLuuxx2L0uo108',
    appId: '1:544154185532:android:44857d3a4ff4723c6bb839',
    messagingSenderId: '544154185532',
    projectId: 'tigris-notes-app',
    storageBucket: 'tigris-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCICDXb2JOv3HkZ5HRKa41bo1Qr68nyBoU',
    appId: '1:544154185532:ios:332c936c7241167a6bb839',
    messagingSenderId: '544154185532',
    projectId: 'tigris-notes-app',
    storageBucket: 'tigris-notes-app.firebasestorage.app',
    iosClientId: '544154185532-ios332c936c7241167a6bb839.apps.googleusercontent.com',
    iosBundleId: 'com.personal.learning.tigris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCICDXb2JOv3HkZ5HRKa41bo1Qr68nyBoU',
    appId: '1:544154185532:ios:332c936c7241167a6bb839',
    messagingSenderId: '544154185532',
    projectId: 'tigris-notes-app',
    storageBucket: 'tigris-notes-app.firebasestorage.app',
    iosClientId: '544154185532-ios332c936c7241167a6bb839.apps.googleusercontent.com',
    iosBundleId: 'com.personal.learning.tigris',
  );
}
